import { Gift, Guest, WeddingSettings } from './types';

export const DEFAULT_SETTINGS: WeddingSettings = {
  brideName: 'Fernanda',
  groomName: 'Gabryel',
  coupleInitials: 'F & G',
  heroSubtitle: 'Vamos celebrar o amor, a cumplicidade e o início do nosso para sempre.',
  weddingDate: '2026-11-21T16:30:00',
  ceremonyVenueName: 'Capela dos Sonhos & Jardins',
  ceremonyAddress: 'Av. das Flores, 1500 - Jardim Botânico, São Paulo - SP',
  ceremonyTime: '16:30',
  ceremonyMapsUrl: 'https://maps.google.com/?q=Jardim+Botanico+Sao+Paulo',
  receptionVenueName: 'Espaço Villa das Palmeiras',
  receptionAddress: 'Av. das Flores, 1550 (Mesmo complexo) - São Paulo - SP',
  receptionTime: '18:30',
  receptionMapsUrl: 'https://maps.google.com/?q=Jardim+Botanico+Sao+Paulo',
  showOrientacoesSection: true,
  showRsvpSection: true,
  dressCodeTitle: 'Passeio Completo / Traje Social',
  dressCodeDescription: 'Para as mulheres: vestidos longos ou mídi em tons suaves ou alegres (pedimos gentilmente evitar branco, off-white e tons de marfim). Para os homens: terno com gravata ou blazer elegante.',
  dressCodeColors: ['#E0A899', '#C2847A', '#8EA89D', '#D9C5B2', '#5B7065', '#2E4057'],
  loveStory: [
    {
      year: '2020',
      title: 'O Primeiro Olhar',
      description: 'Nos conhecemos em uma cafeteria numa tarde de outono. Uma conversa que era para durar 15 minutos virou horas de risadas e afinidades.',
      imageUrl: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=800&q=80',
    },
    {
      year: '2022',
      title: 'A Primeira Viagem Juntos',
      description: 'Descobrimos nosso amor compartilhado por viajar, conhecer novos sabores e colecionar pores do sol. Foi quando tivemos certeza de que éramos um só.',
      imageUrl: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?auto=format&fit=crop&w=800&q=80',
    },
    {
      year: '2024',
      title: 'O Pedido de Casamento',
      description: 'Sob um céu estrelado na praia, com o som das ondas e o coração disparado, o "SIM" mais emocionante e feliz de nossas vidas.',
      imageUrl: 'https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&w=800&q=80',
    },
    {
      year: '2026',
      title: 'O Grande Dia',
      description: 'Agora, com todos que amamos reunidos, daremos o passo mais importante da nossa jornada: o nosso casamento!',
      imageUrl: 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
    },
  ],
  
  // PIX Config
  pixKey: 'fernanda.gabryel.casamento@gmail.com',
  pixKeyType: 'email',
  pixMerchantName: 'FERNANDA E GABRYEL',
  pixMerchantCity: 'SAO PAULO',

  // Evolution API Config
  evolutionApiUrl: 'https://api.gabryelamaro.com/message/sendText/BarmanJF',
  evolutionApiKey: 'sua_api_key_aqui',
  evolutionInstanceName: 'BarmanJF',

  // MinIO S3 Object Storage Config
  minioEndpoint: 'https://s3.gabryelamaro.com',
  minioPort: 443,
  minioUseSSL: true,
  minioAccessKey: '3Lut3Uey3fSGdVb8gL6b',
  minioSecretKey: 'nNN4YwBcJPtiwvRimGTDiJZp1W6SP0jKjsM46PlI',
  minioBucketName: 'casamento',
  minioPublicUrl: 'https://s3.gabryelamaro.com/casamento',

  // Admin & Features
  adminPin: '1234',
  postEventPhotosEnabled: true,
  sectionOrder: ['historia', 'local', 'orientacoes', 'presentes', 'duvidas', 'rsvp', 'fotos'],
};

export const DEFAULT_GIFTS: Gift[] = [
  // --- PRESENTES DIVERTIDOS & BRINCADEIRAS MALUCAS ---
  {
    id: 'gift-fun-1',
    title: '🧘 Calmante para os Noivos não Surtarem no Altar',
    description: 'Para manter a paz de espírito, a pressão arterial e o sorriso dos noivos sob controle.',
    category: 'brincadeiras',
    price: 45.00,
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 15,
    quotaPurchased: 3,
    isFeatured: true,
    active: true,
  },
  {
    id: 'gift-fun-2',
    title: '🍹 Uma Rodada de Caipirinhas na Beira da Piscina',
    description: 'Para os noivos brindarem à liberdade de nunca mais ver uma planilha de orçamento de casamento.',
    category: 'brincadeiras',
    price: 60.00,
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 20,
    quotaPurchased: 4,
    isFeatured: true,
    active: true,
  },
  {
    id: 'gift-fun-3',
    title: '🔇 Tampão de Ouvido Anti-Ronco para a Noiva',
    description: 'Para a Fernanda conseguir dormir em paz quando o Gabryel ligar o motor de caminhão à noite.',
    category: 'brincadeiras',
    price: 35.00,
    imageUrl: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 10,
    quotaPurchased: 2,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-fun-4',
    title: '🎮 1 Hora de Videogame / Futebol sem Levar Bronca',
    description: 'Um voucher mágico concedido ao noivo para jogar com os amigos com imunidade matrimonial.',
    category: 'brincadeiras',
    price: 80.00,
    imageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 10,
    quotaPurchased: 1,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-fun-5',
    title: '🧯 Extintor de Incêndio para a Primeira DR de Casados',
    description: 'Apaga qualquer discussão sobre quem esqueceu a toalha molhada em cima da cama nova.',
    category: 'brincadeiras',
    price: 50.00,
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 10,
    quotaPurchased: 2,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-fun-6',
    title: '🍫 Reserva Emergencial de Chocolate para TPM da Noiva',
    description: 'Investimento direto na sobrevivência, paciência e harmonia matrimonial do Gabryel.',
    category: 'brincadeiras',
    price: 65.00,
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 15,
    quotaPurchased: 5,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-fun-7',
    title: '🍕 Rodízio de Pizza da Madrugada Pós-Festa',
    description: 'Para curar a ressaca do casamento no dia seguinte comendo pizza gelada deitados no sofá.',
    category: 'brincadeiras',
    price: 90.00,
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 8,
    quotaPurchased: 1,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-fun-8',
    title: '🧺 Manual Ilustrado: Como Dobrar Lençol de Elástico',
    description: 'O maior mistério da humanidade e da vida adulta finalmente resolvido para os noivos.',
    category: 'brincadeiras',
    price: 30.00,
    imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 10,
    quotaPurchased: 0,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-fun-9',
    title: '📜 Contrato Registrado em Cartório de Quem Lava a Louça',
    description: 'Documento oficial com firma reconhecida para evitar a pergunta: "De quem é a vez hoje no domingo?"',
    category: 'brincadeiras',
    price: 70.00,
    imageUrl: 'https://images.unsplash.com/photo-1585837575652-267c041d77d4?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 6,
    quotaPurchased: 1,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-fun-10',
    title: '🩴 Havaianas Turbinadas para a Noiva Descer do Salto na Pista',
    description: 'Equipamento de segurança obrigatório para a Fernanda dançar até as 5h sem dor no pé.',
    category: 'brincadeiras',
    price: 38.00,
    imageUrl: 'https://images.unsplash.com/photo-1562183241-b937e95585b6?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 12,
    quotaPurchased: 2,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-fun-11',
    title: '🕶️ Óculos Escuros para o Noivo Disfarçar o Choro no Altar',
    description: 'Ele jura que não chora em casamento, mas vai cair uma lágrima na entrada triunfal da noiva.',
    category: 'brincadeiras',
    price: 42.00,
    imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 8,
    quotaPurchased: 1,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-fun-12',
    title: '🍟 Pedágio do McDonald\'s na Volta da Balada',
    description: 'Combo com 2 quarteirões e batata frita grande para matar a fome dos noivos às 4h da manhã.',
    category: 'brincadeiras',
    price: 55.00,
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 10,
    quotaPurchased: 3,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-fun-13',
    title: '🎬 1 Mês de Decisão Rápida do que Assistir na Netflix',
    description: 'Cota mágica para acabar com as 2 horas diárias gastas apenas escolhendo o filme.',
    category: 'brincadeiras',
    price: 85.00,
    imageUrl: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 5,
    quotaPurchased: 0,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-fun-14',
    title: '🍷 Taça Gigante para Ouvir as Fofocas do Trabalho',
    description: 'Capacidade para 1 garrafa inteira. Essencial para desabafar depois de um dia corrido.',
    category: 'brincadeiras',
    price: 65.00,
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 10,
    quotaPurchased: 2,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-fun-15',
    title: '🧦 Detector Magnético de Meias Perdidas embaixo da Cama',
    description: 'Tecnologia da NASA para achar os pares de meias que o noivo largou pelo quarto.',
    category: 'brincadeiras',
    price: 32.00,
    imageUrl: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 10,
    quotaPurchased: 0,
    isFeatured: false,
    active: true,
  },

  // --- CASA, COZINHA & LUA DE MEL TRADICIONAIS ---
  {
    id: 'gift-1',
    title: 'Jogo de Cama 400 Fios Queen',
    description: 'Para os noivos dormirem nas nuvens depois de organizar esse casamento maravilhoso.',
    category: 'casa',
    price: 320.00,
    imageUrl: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 1,
    quotaPurchased: 0,
    isFeatured: true,
    active: true,
  },
  {
    id: 'gift-2',
    title: 'Jantar Romântico na Lua de Mel',
    description: 'Um jantar à luz de velas com vinho e vista para o mar inesquecível para os recém-casados.',
    category: 'lua-de-mel',
    price: 250.00,
    imageUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 4,
    quotaPurchased: 1,
    isFeatured: true,
    active: true,
  },
  {
    id: 'gift-3',
    title: 'Cafeteira Expresso dos Noivos',
    description: 'Para garantir a dose diária de amor e energia nas manhãs da nossa nova casa.',
    category: 'cozinha',
    price: 450.00,
    imageUrl: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 1,
    quotaPurchased: 0,
    isFeatured: true,
    active: true,
  },
  {
    id: 'gift-4',
    title: 'Cota Diária de Hotel na Lua de Mel',
    description: 'Contribua com uma diária inesquecível no resort com vista paradisíaca.',
    category: 'lua-de-mel',
    price: 380.00,
    imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 5,
    quotaPurchased: 1,
    isFeatured: true,
    active: true,
  },
  {
    id: 'gift-5',
    title: 'Aparelho de Jantar 30 Peças de Porcelana',
    description: 'Para receber os padrinhos e a família com elegância e requinte nos domingos.',
    category: 'casa',
    price: 520.00,
    imageUrl: 'https://images.unsplash.com/photo-1615865417491-9941019fbc00?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 1,
    quotaPurchased: 0,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-6',
    title: 'Fritadeira Air Fryer Digital Inox',
    description: 'Para preparar petiscos saudáveis e rápidos nas noites de cinema em casa.',
    category: 'cozinha',
    price: 290.00,
    imageUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 1,
    quotaPurchased: 0,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-7',
    title: 'Passeio de Barco ao Pôr do Sol na Lua de Mel',
    description: 'Uma tarde mágica navegando pelas águas cristalinas com champanhe.',
    category: 'experiencias',
    price: 310.00,
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 2,
    quotaPurchased: 0,
    isFeatured: false,
    active: true,
  },
  {
    id: 'gift-8',
    title: 'Kit Churrasco Completo dos Noivos',
    description: 'Para os domingos de churrasco na casa nova com os amigos e padrinhos.',
    category: 'cozinha',
    price: 180.00,
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80',
    quotaTotal: 1,
    quotaPurchased: 0,
    isFeatured: false,
    active: true,
  }
];

export const DEFAULT_GUESTS: Guest[] = [
  {
    id: 'guest-1',
    name: 'Carlos Eduardo Oliveira',
    phone: '11987654321',
    email: 'carlos.oliveira@email.com',
    slug: 'carlos-eduardo-oliveira',
    maxCompanions: 2,
    status: 'reconfirmed',
    confirmedCompanions: [
      { name: 'Mariana Castro Oliveira', isChild: false },
      { name: 'Enzo Oliveira', isChild: true }
    ],
    dietRestrictions: 'Mariana é vegetariana',
    message: 'Estamos muito honrados pelo convite! Estaremos presentes para celebrar esse momento lindo com vocês!',
    reminderCount: 2,
    lastReminderSentAt: '2026-08-10T14:30:00Z',
    reconfirmedAt: '2026-08-20T18:40:00Z',
    attendedOnDay: false,
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'guest-2',
    name: 'Juliana Mendes',
    phone: '11999887766',
    email: 'juliana.mendes@email.com',
    slug: 'juliana-mendes',
    maxCompanions: 1,
    status: 'confirmed',
    confirmedCompanions: [
      { name: 'Rodrigo Alcantara', isChild: false }
    ],
    dietRestrictions: '',
    message: 'Amigos queridos! Contem com nossa presença e animação na pista!',
    reminderCount: 1,
    lastReminderSentAt: '2026-08-12T19:00:00Z',
    attendedOnDay: false,
    createdAt: '2026-07-02T11:30:00Z',
  },
  {
    id: 'guest-3',
    name: 'Roberto & Família Martins',
    phone: '11977665544',
    email: 'roberto.martins@email.com',
    slug: 'roberto-familia-martins',
    maxCompanions: 3,
    status: 'pending',
    confirmedCompanions: [],
    dietRestrictions: '',
    message: '',
    reminderCount: 1,
    lastReminderSentAt: '2026-08-15T09:00:00Z',
    attendedOnDay: false,
    createdAt: '2026-07-05T14:00:00Z',
  },
  {
    id: 'guest-4',
    name: 'Beatriz Vasconcelos',
    phone: '21988776655',
    email: 'beatriz.v@email.com',
    slug: 'beatriz-vasconcelos',
    maxCompanions: 0,
    status: 'declined',
    confirmedCompanions: [],
    dietRestrictions: '',
    message: 'Infelizmente terei um compromisso profissional inadiável fora do país nessa data. Desejo todo o amor do mundo a vocês!',
    reminderCount: 1,
    lastReminderSentAt: '2026-08-10T12:00:00Z',
    attendedOnDay: false,
    createdAt: '2026-07-08T16:20:00Z',
  }
];
